logging:
  level:
    root: INFO

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:log4jdbc:postgresql://localhost:5432/ys_local
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: young
    password: asdf1234%
  sql:
    init:
      schema-locations: classpath*:schema/create.sql
      encoding: UTF-8
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: TVNDLVVTRVItU0VDUkVULUZPUi1BVVRIT1JJWkFUSU9O

aes:
  user-secret: Q1RNUy1QUk9ELU9GLUVOQ1JZUFRJT04K

api-key:
  header: X-API-Key
  value:
    user: QVBJLUtFWS1GT1ItTVNDLVVTRVI=

base-host: http://localhost:9000
