server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    gateway:
      routes:
        - id: first-service
          predicates:
            - Path=/a-service/**
          uri: lb://a-service
          filters:
            - RewritePath=/a-service/(?<segment>.*), /$\{segment}

        - id: second-service
          predicates:
            - Path=/b-service/**
          uri: lb://B-SERVICE
          filters:
            - RewritePath=/b-service/(?<segment>.*), /$\{segment}