server:
  port: 8761

eureka:
  server:
    enable-self-preservation: true
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 30000
  client:
    register-with-eureka: false
    fetch-registry: false
