server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.cloud.hostname}:${spring.application.instance_id:${random:value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka